---
- name: Install Nginx + repositories + configuring
  hosts: all
  become: yes

  tasks:
    - name: download PGP-key
      get_url:
        url: https://nginx.org/keys/nginx_signing.key
        dest: /etc/nginx_signing.key

    - name: install PGP-key
      apt_key:
        file: /etc/nginx_signing.key
        state: present

    - name: Add Nginx Repo deb
      apt_repository:
        repo: deb https://nginx.org/packages/mainline/debian/ buster nginx

    - name: Add Nginx Repo deb-src
      apt_repository:
        repo: deb-src https://nginx.org/packages/mainline/debian/ buster nginx

    - name: Delete Nginx-common
      apt: name=nginx-common state=absent

    - name: Install Nginx of Debian 10
      apt: name=nginx update_cache=yes state=latest

    - name: Start Nginx and Enable it on the every boot
      service: name=nginx state=started enabled=yes

    - name: copy the nginx config file and restart nginx
      copy:
        src: conf/test.conf
        dest: /etc/nginx/sites-available/test.conf
    - name: create symlink
      file:
          src: /etc/nginx/sites-available/test.conf
          dest: /etc/nginx/sites-enabled/test
          state: link
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes


