version: "3.7"
services:
    php-cli:
        build:
            context: ./infrastructure/development/docker/debian/php-cli
            dockerfile: Dockerfile
        volumes:
            - ./backend:/pure/backend
    php-fpm:
        build:
            context: ./infrastructure/development/docker/debian/php-fpm
            dockerfile: Dockerfile
        volumes:
            - ./backend:/pure/backend
    nginx-backend:
        build:
            context: ./infrastructure/development/docker/debian/nginx-backend
            dockerfile: Dockerfile
        ports:
            - "8081:8081"
        volumes:
            - ./backend:/pure/backend
        depends_on:
            - php-fpm
    postgres:
        image: postgres:13
        environment:
            POSTGRES_USER: alex
            POSTGRES_PASSWORD: test
            POSTGRES_DB: pure
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_USER: alex
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: pure
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"
    nginx-frontend:
        build:
            context: ./infrastructure/development/docker/debian/nginx-frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./frontend:/pure/frontend
        depends_on:
            - node
    node:
        build:
            context: ./infrastructure/development/docker/debian/node
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/pure/frontend
        command: yarn start
        tty: true
    node-cli:
        build:
            context: ./infrastructure/development/docker/debian/node
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/pure/frontend
volumes:
    postgres:
    mysql:
