version: "3.7"
services:
    php-cli:
        build:
            context: ./infrastructure/development/docker/debian/php-cli
            dockerfile: Dockerfile
        volumes:
            - ./:/pure
    php-fpm:
        build:
            context: ./infrastructure/development/docker/debian/php-fpm
            dockerfile: Dockerfile
        volumes:
            - ./:/pure
    nginx:
        build:
            context: ./infrastructure/development/docker/debian/nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./:/pure
        depends_on:
            - php-fpm
    postgres:
        image: postgres:13
        environment:
            POSTGRES_USER: alex
            POSTGRES_PASSWORD: test
            POSTGRES_DB: pure
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"
volumes:
    postgres:
