---
-   name: Upgrade
    hosts: all
    remote_user: root
    any_errors_fatal: true
    vars_files:
      - vars/vars.yml
    tasks:
      -   name: Update APT package cache
          apt:
            update_cache: yes
          register: out

      -   name: Upgrade APT to the latest packages
          apt:
            upgrade: dist
          register: out

      -   name: Remove useless packages
          apt:
            autoclean: yes
          register: out

      -   name: Remove useless dependencies
          apt:
            autoremove: yes
          register: out
      - debug:
          var: out